### ISSUE TITLE
broken import =}

### ISSUE THREAD

**Issue by TrejGun** [vanishdark/nestjs-oauth2-example#2]
https://github.com/vanishdark/nestjs-oauth2-example/blob/ab6e2db8deb74feda8b0cca1f7b2df454393d2e7/src/controllers/auth/auth.controller.ts#L1

**Comment by vanishdark** [comment]
Thanks @TrejGun, the repo is now in gitlab https://gitlab.com/vanishdark/nestjs-oauth2-example
